[package]
name = "fourier-series-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
oorandom = "11.1.3"
getrandom = "0.2.11"
rand = "0.8.5"
svg = "0.13.1"
plotters = "0.3.5"
num = "0.4.3"